### ISSUE TITLE
リバースモードの書き込み

### ISSUE THREAD

**Issue by MasatoKubotera** [citbrains/B3MServoChecker#4]
最新コミット[9fe75d3250f1d570e8e8d240e17fe4cb1fdd7547](https://github.com/citbrains/B3MServoChecker/tree/9fe75d3250f1d570e8e8d240e17fe4cb1fdd7547)において，「Set Parameters」を使ってパラメータを書き込んでも，リバースモードが行えない（実装されていない？）ことが確認できた．

GankenKun Ver3.0，SUSTAINA-OP Ver1.0共通でID３，４，７，１２，１３，１６をリバースモードにすることが必要である．

この作業を手操作で行っていると，効率が悪く，間違える恐れもある．
最悪の場合，リバースモードを行っていないまたはリバースモードを行うIDを間違えると直立姿勢時（HR）は問題ないが，Ready姿勢において可動範囲を超えサーボを破壊する恐れがある．

そのため，「Set Parameters」内の処理にリバースモードの書き込みの実装をお願いしたい．

**Comment by yasuohayashibara** [comment]
以下の仕様に基づいてサーボモータのパラメータを書き込んでいます．

https://github.com/citbrains/citbrains_humanoid/wiki/B3M%E3%80%80%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E8%A8%AD%E5%AE%9A

林原としてはそもそも間違いを無くすためには，一斉に切り替えられるのであれば全てのサーボモータのリバースモードをなくしてhr46_b3mを書き換えたほうが良いかなという気もします．

例えば以下のようなミスをおそれます．

・リバースが設定されているサーボモータを，IDだけ変えてリバースで無い関節に利用して逆向きに動く．
　（必ずB3MServoCheckerを使用してもらえれば避けられるミスですが．．．）

だいぶ分かっている方でないとどの関節がリバースかを把握していないと思いますので，（特に慌てている試合中などに）頻繁に起きそうなミスのような気がします．

ちなみに，おそらく以下のdeg_signを切り替えれば回転方向が変わります．
こちらの方がよりミスが発生しにくい解決策だと思います．
すでにマイナスもありますが，おそらくAcceliteの回転方向に合わせていると思われます．

https://github.com/citbrains/citbrains_humanoid/blob/b4e4c64af6522f46a8e287869df1c80edb887662/for2050/src/hr46_rs/serv_init.c#L52-L114

**Comment by hiroki-0001** [comment]
こちらの問題ですが、林原先生のおっしゃる通り、https://github.com/citbrains/citbrains_humanoid/blob/b4e4c64af6522f46a8e287869df1c80edb887662/for2050/src/hr46_rs/serv_init.c#L52-L114
のdeg_signを切り替えれば回転方向が変わりました。
現状はRS485変換基版に対応したコードがまだmasterにマージされていないこともあり、この設定の反映を行うことはできませんが、それが終わり次第、この設定の反映を行いたいと思います

**Comment by yasuohayashibara** [comment]
全体で合意を取って一斉に変更したほうが良いと思いますが，こちらはとりあえずペンディングで良いでしょうか？

> GankenKun Ver3.0，SUSTAINA-OP Ver1.0共通でID３，４，７，１２，１３，１６をリバースモードにすることが必要である．

**Comment by hiroki-0001** [comment]
リバースモードの機能の廃止に関しては世界大会後に行いたいと思います。
またその変更に関する議論などは以下のissueで行いたいと思います。
https://github.com/citbrains/citbrains_humanoid/issues/1787

**Comment by hiroki-0001** [comment]
このissueはcloseします

**Comment by hiroki-0001** [comment]
権限なくてcloseできませんでしたので、権限ある方closeしてもらえると助かります

**Comment by yasuohayashibara** [comment]
なるほど．
みなさんがアクセスできるように変更しましたので，閉じていただければと思います．

**Comment by hiroki-0001** [comment]
ありがとうございます。closeします
